#!/usr/bin/env python

#   Copyright 2012 Oli Schacher
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
#
# main startup file

import ConfigParser
from postomaat import POSTOMAAT_VERSION
from postomaat.daemon import DaemonStuff
import logging
import logging.config
import postomaat.funkyconsole
import sys
from postomaat.core import MainController
import signal
import os
import pwd
import grp

controller=None

theconfigfile='/etc/postomaat/postomaat.conf'
dconfdir='/etc/postomaat/conf.d'
theloggingfile='/etc/postomaat/logging.conf'



def reloadconfig():
    """reload configuration file"""
    logger=logging.getLogger('postomaat')
    logger.info('Reloading configuration')
    newconfig=ConfigParser.ConfigParser()
    newconfig.readfp(open(theconfigfile))
    
    identifier="no identifier given"
    if newconfig.has_option('main', 'identifier'):
        identifier=newconfig.get('main','identifier')
    
    #load conf.d
    if os.path.isdir(dconfdir):
        filelist=os.listdir(dconfdir)
        configfiles=[dconfdir+'/'+c for c in filelist if c.endswith('.conf')]
        logger.debug('Conffiles in %s: %s'%(dconfdir,configfiles))
        readfiles=newconfig.read(configfiles)
        logger.debug('Read additional files: %s'%(readfiles))

    logger.info('Reload config complete. Current configuration:%s'%identifier)
    controller.config=newconfig
    controller.propagate_core_defaults()
    
    logger.info('Reloading plugins...')
    ok=controller.load_plugins()
    if ok:
        logger.info('Plugin reload completed')
    else:
        logger.error('Plugin reload failed')
    
    controller.propagate_plugin_defaults()
    
    controller.reload()

def sighup(signum,frame):
    """handle sighup to reload config"""
    reloadconfig()

lint=False
debugmsg=False

if "--lint" in sys.argv:
    lint=True

if '--test' in sys.argv:
    debugmsg=True

if '--help' in sys.argv:
    print "Usage:"
    print "postomaat --lint [--debug] to check config"
    print "--test [--debug] attr=val attr=val ...   to test a message/debug postomaat"
    print "--attrs to print a list of supported policy attributes"
    sys.exit(0)

if "--version" in sys.argv:
    print "Postomaat Version %s"%POSTOMAAT_VERSION
    sys.exit(0) 

defaultattrs={
    #Postfix version 2.1 and later:
    'request':'smtpd_access_policy',
    'protocol_state':'RCPT',
    'protocol_name':'SMTP',
    'helo_name':'smtp.example.com',
    'queue_id':'8045F2AB23',
    'sender':'sender@example.com',
    'recipient':'recipient@example.org',
    'recipient_count':'1',
    'client_address':'1.2.3.4',
    'client_name':'host.example.net',
    'reverse_client_name':'host.example.net',
    'instance':'123.456.7',
    #Postfix version 2.2 and later:
    'sasl_method':'',
    'sasl_username':'',
    'sasl_sender':'',
    'size':'12345',
    'ccert_subject':'',
    'ccert_issuer':'',
    'ccert_fingerprint':'',
    #Postfix version 2.3 and later:
    'encryption_protocol':'TLSv1/SSLv3',
    'encryption_cipher':'DHE-RSA-AES256-SHA',
    'encryption_keysize':'256',
    'etrn_domain':'',
    #Postfix version 2.5 and later:
    'stress':'',
}

if '--attrs' in sys.argv:
    print "Supported attributes and their default:"
    print "See http://www.postfix.org/SMTPD_POLICY_README.html#protocol for a full description"
    print ""
    for k,v in defaultattrs.iteritems():
        print "%s : %s"%(k,v)
    sys.exit(0)


config=ConfigParser.ConfigParser()
if not os.path.exists(theconfigfile):
    print """Configfile (%s) not found. Please create it by renaming the .dist file and modifying it to your needs"""%theconfigfile
    sys.exit(1)
readconfig=config.readfp(open(theconfigfile))
#load conf.d
if os.path.isdir(dconfdir):
    filelist=os.listdir(dconfdir)
    configfiles=[dconfdir+'/'+c for c in filelist if c.endswith('.conf')]
    readfiles=config.read(configfiles)


daemon=DaemonStuff('/var/run/postomaat.pid')
#we could have an empty config file
if  not (lint or debugmsg): #no daemon for lint
    if config.has_option('main', 'daemonize'):
        if config.getboolean('main', 'daemonize'):
            daemon.createDaemon()
    else: #option not specified -> default to run daemon
        daemon.createDaemon()
        
if lint or debugmsg:
    level=logging.INFO
    if '--debug' in sys.argv:
        level=logging.DEBUG
        
    logging.basicConfig(level=level)
    
    fc=postomaat.funkyconsole.FunkyConsole()
    print fc.strcolor("postomaat", "yellow"),
    print fc.strcolor(POSTOMAAT_VERSION, "green")
else:
    logging.config.fileConfig(theloggingfile)

controller=MainController(config)
controller.propagate_core_defaults()
baselogger=logging.getLogger('')
baselogger.info("postomaat Version %s starting up"%POSTOMAAT_VERSION)

try:
    running_user=config.get('main','user')
    running_group=config.get('main','group')
except:
    running_user='nobody'
    running_group='nobody'
daemon.drop_privs(running_user,running_group)




if lint:
    controller.lint()
elif debugmsg:    
    attrs=defaultattrs.copy()
    
    for arg in sys.argv:
        if not '=' in arg:
            continue
        
        key,value=arg.split('=',1)
        
        if key in defaultattrs:
            attrs[key]=value
        else:
            print "Warning: %s ignored - unsupported attribute"%key
    print attrs
    action,arg=controller.test(attrs)
    if arg==None:
        arg=""
    print "Result: %s %s"%(action.upper(),arg)
else:
    signal.signal(signal.SIGHUP, sighup)
    controller.startup()


