#!/bin/sh
#
# Startup script for postomaat
#
# chkconfig: 2345 65 38
# description: Postomaat Policy Daemon
# processname: postomaat
# pidfile: /var/run/postomaat.pid

# Source function library.
. /etc/rc.d/init.d/functions

# Source networking configuration.
. /etc/sysconfig/network

# See how we were called.
case "$1" in
  start)
        echo -n "Starting Postomaat Policy Daemon: "
        daemon /usr/bin/postomaat --pidfile=/var/run/postomaatd.pid
        RETVAL=$?
        echo
        ;;
  stop)
        echo -n "Stopping Postomaat Policy Daemon: "
        killproc postomaat
        rm -f /var/run/postomaat.pid
        RETVAL=$?
        echo
        ;;
  status)
        status postomaat
        RETVAL=$?
        ;;
  restart)
        $0 stop
        $0 start
        RETVAL=$?
        ;;
  reload)
  		echo -n "Reloading postomaat config: "
        killproc postomaat -HUP
        RETVAL=$?
        echo
        ;;
  		
  *)
        echo "Usage: postomaat {start|stop|status|restart|reload}"
        exit 1
esac

exit $RETVAL
